PROYECTO FINAL ALSE: MainWindow Class Reference
MainWindow Class Reference
Controlador principal de la aplicación de gestión de inventario.
#include <mainwindow.h>
Public Member Functions
MainWindow (QSqlDatabase db, QWidget *parent=nullptr)
Constructor de la ventana principal.
Private Slots
void onEdit ()
Inicia el proceso de edición del componente seleccionado.
void onAdd ()
Abre el diálogo para agregar un nuevo componente al inventario.
void onDelete ()
Elimina el registro seleccionado en la tabla.
void onExport ()
Genera y exporta un reporte del inventario en formato CSV.
void onLowStock ()
Analiza el stock actual y resalta visualmente los ítems críticos.
void onSearch (const QString &text)
Filtra la tabla en tiempo real según el texto ingresado.
Private Member Functions
void refreshModel ()
Actualiza la vista recargando los datos desde la base de datos SQL.
void checkLowStockOnStart ()
void onLoadDefaults ()
Carga un conjunto de datos de prueba (Seed Data).
void onRestoreDefaults ()
Restaura la base de datos a su estado original (vacía y luego recargada).
Private Attributes
InventoryManager manager
QSqlQueryModel * model
QSortFilterProxyModel * proxy
QTableView * tableView
QLineEdit * searchEdit
const int lowStockThreshold = 5
Detailed Description
Controlador principal de la aplicación de gestión de inventario.
Esta clase orquesta la interacción entre el usuario y la base de datos. Sus responsabilidades incluyen:
Inicializar la base de datos y la interfaz de usuario.
Gestionar el modelo de datos (QSqlQueryModel) y el filtrado (QSortFilterProxyModel).
Manejar eventos de botones (CRUD, exportación, restauración).
Aplicar delegados personalizados para la visualización (LowStockDelegate).
Definition at line 65 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QSqlDatabase db, QWidget * parent = nullptr) explicit
Constructor de la ventana principal.
Inicializa la conexión a la base de datos, configura el layout principal, crea los modelos de datos y conecta todas las señales de la interfaz.
Parameters
db Referencia a la conexión de base de datos QSqlDatabase ya inicializada.
parent Widget padre (opcional).
Definition at line 184 of file mainwindow.cpp.
    : QWidget(parent), manager(db)
{
    setWindowTitle("Gestión de Inventario");
    resize(1000, 600);
    QVBoxLayout *mainLayout = new QVBoxLayout(this);
    QHBoxLayout *topLayout = new QHBoxLayout();
    // -- Inicialización de Widgets --
    searchEdit = new QLineEdit(); searchEdit->setPlaceholderText("Buscar...");
    QPushButton *btnAdd = new QPushButton("Agregar");
    QPushButton *btnDelete = new QPushButton("Eliminar seleccionado");
    QPushButton *btnExport = new QPushButton("Exportar CSV");
    QPushButton *btnLowStock = new QPushButton("Revisar stock bajo");
    QPushButton *btnLoadDefaults = new QPushButton("Cargar base por defecto");
    QPushButton *btnRestore = new QPushButton("Restaurar base original");
    QPushButton *btnEdit = new QPushButton("Editar");
    // -- Construcción del Layout Superior --
    topLayout->addWidget(btnLoadDefaults);
    topLayout->addWidget(btnRestore);
    topLayout->addWidget(btnEdit);
    topLayout->addWidget(new QLabel("Buscar:"));
    topLayout->addWidget(searchEdit);
    topLayout->addWidget(btnAdd);
    topLayout->addWidget(btnDelete);
    topLayout->addWidget(btnLowStock);
    topLayout->addWidget(btnExport);
    mainLayout->addLayout(topLayout);
    // -- Configuración del Modelo MVC --
    model = new QSqlQueryModel(this);
    // Configuración del Proxy para filtrado y ordenamiento
    proxy = new QSortFilterProxyModel(this);
    proxy->setSourceModel(model);
    proxy->setFilterCaseSensitivity(Qt::CaseInsensitive);
    proxy->setFilterKeyColumn(-1); // Filtrar en todas las columnas
    // -- Configuración de la Tabla (Vista) --
    tableView = new QTableView();
    tableView->setModel(proxy);
    tableView->setSelectionBehavior(QAbstractItemView::SelectRows);
    tableView->setSelectionMode(QAbstractItemView::SingleSelection);
    tableView->setEditTriggers(QAbstractItemView::NoEditTriggers); // Edición solo vía diálogo
    // Inyección del delegado para resaltar stock bajo
    tableView->setItemDelegate(new LowStockDelegate(lowStockThreshold, this));
    mainLayout->addWidget(tableView);
    // -- Conexiones de Señales y Slots --
    connect(btnAdd, &QPushButton::clicked, this, &MainWindow::onAdd);
    connect(btnDelete, &QPushButton::clicked, this, &MainWindow::onDelete);
    connect(btnExport, &QPushButton::clicked, this, &MainWindow::onExport);
    connect(btnLowStock, &QPushButton::clicked, this, &MainWindow::onLowStock);
    connect(searchEdit, &QLineEdit::textChanged, this, &MainWindow::onSearch);
    connect(btnLoadDefaults, &QPushButton::clicked, this, &MainWindow::onLoadDefaults);
    connect(btnRestore, &QPushButton::clicked, this, &MainWindow::onRestoreDefaults);
    connect(btnEdit, &QPushButton::clicked, this, &MainWindow::onEdit);
    // Inicialización de la tabla en BD si no existe
    if (!manager.createTable()) {
        QMessageBox::critical(this, "Error Crítico", "No se pudo crear o verificar la tabla de inventario en la base de datos.");
    }
    refreshModel();
}
References InventoryManager::createTable(), lowStockThreshold, manager, model, onAdd(), onDelete(), onEdit(), onExport(), onLoadDefaults(), onLowStock(), onRestoreDefaults(), onSearch(), proxy, refreshModel(), searchEdit, and tableView.
Member Function Documentation
checkLowStockOnStart()
void MainWindow::checkLowStockOnStart () private
onAdd
void MainWindow::onAdd () private slot
Abre el diálogo para agregar un nuevo componente al inventario.
Crea una instancia de AddDialog y conecta su señal de aceptación para insertar el nuevo registro mediante InventoryManager.
Definition at line 323 of file mainwindow.cpp.
{
    AddDialog *dlg = new AddDialog();
    dlg->setWindowModality(Qt::ApplicationModal);
    dlg->show();
    connect(dlg, &AddDialog::accepted, this, [this, dlg]() {
        if (dlg->getName().isEmpty() || dlg->getType().isEmpty()) {
            QMessageBox::warning(this, "Validación", "Nombre y tipo son obligatorios.");
            return;
        }
        Component c(0,
                    dlg->getName(),
                    dlg->getType(),
                    dlg->getQuantity(),
                    dlg->getLocation(),
                    dateToString(dlg->getDate()));
        if (!manager.addItem(c.getName(), c.getType(), c.getQuantity(), c.getLocation(), c.getPurchaseDate())) {
            QMessageBox::critical(this, "Error", "No se pudo insertar el componente en la base de datos.");
        } else {
            refreshModel();
        }
        dlg->close();
        dlg->deleteLater();
    });
    connect(dlg, &AddDialog::cancelled, dlg, &AddDialog::close);
}
References AddDialog::accepted(), InventoryManager::addItem(), AddDialog::cancelled(), dateToString(), AddDialog::getDate(), AddDialog::getLocation(), AddDialog::getName(), AddDialog::getQuantity(), AddDialog::getType(), manager, and refreshModel().
onDelete
void MainWindow::onDelete () private slot
Elimina el registro seleccionado en la tabla.
Muestra un cuadro de confirmación antes de proceder. Si se confirma, solicita al InventoryManager la eliminación por ID.
Definition at line 359 of file mainwindow.cpp.
{
    QModelIndexList sel = tableView->selectionModel()->selectedRows();
    if (sel.isEmpty()) {
        QMessageBox::information(this, "Eliminar", "Selecciona una fila para eliminar.");
        return;
    }
    QModelIndex idx = sel.first();
    QModelIndex src = proxy->mapToSource(idx);
    int id = model->data(model->index(src.row(), 0)).toInt();
    if (QMessageBox::question(this, "Confirmar Eliminación",
                              QString("¿Estás seguro de eliminar el registro con ID %1?").arg(id)) == QMessageBox::Yes)
    {
        if (!manager.removeItem(id)) {
            QMessageBox::critical(this, "Error", "No se pudo eliminar el registro.");
        } else {
            refreshModel();
        }
    }
}
References manager, model, proxy, refreshModel(), InventoryManager::removeItem(), and tableView.
onEdit
void MainWindow::onEdit () private slot
Inicia el proceso de edición del componente seleccionado.
Recupera el ID del item seleccionado en la tabla, consulta sus datos actuales desde la base de datos, y abre un AddDialog precargado con dicha información.
Note
Utiliza una función lambda para manejar la señal accepted del diálogo, capturando el ID para realizar el updateItem.
Definition at line 263 of file mainwindow.cpp.
{
    QModelIndexList sel = tableView->selectionModel()->selectedRows();
    if (sel.isEmpty()) {
        QMessageBox::information(this, "Editar", "Por favor, selecciona una fila primero.");
        return;
    }
    // Mapeo del índice del proxy al índice del modelo fuente para obtener el ID real
    QModelIndex idx = sel.first();
    QModelIndex src = proxy->mapToSource(idx);
    int id = model->data(model->index(src.row(), 0)).toInt();
    InventoryItem it = manager.getItemById(id);
    AddDialog *dlg = new AddDialog();
    dlg->setWindowModality(Qt::ApplicationModal);
    // Precargar datos en los widgets del diálogo usando findChild
    dlg->findChild<QLineEdit*>("nameEdit")->setText(it.nombre);
    dlg->findChild<QLineEdit*>("typeEdit")->setText(it.tipo);
    dlg->findChild<QSpinBox*>("qtySpin")->setValue(it.cantidad);
    dlg->findChild<QLineEdit*>("locEdit")->setText(it.ubicacion);
    dlg->findChild<QDateEdit*>("dateEdit")->setDate(QDate::fromString(it.fechaAdquisicion, "yyyy-MM-dd"));
    dlg->show();
    // Lógica al aceptar el diálogo
    connect(dlg, &AddDialog::accepted, this, [this, dlg, id]() {
        if (dlg->getName().isEmpty() || dlg->getType().isEmpty()) {
            QMessageBox::warning(this, "Validación", "Nombre y tipo son campos obligatorios.");
            return;
        }
        if (!manager.updateItem(
                id,
                dlg->getName(),
                dlg->getType(),
                dlg->getQuantity(),
                dlg->getLocation(),
                dlg->getDate().toString("yyyy-MM-dd")))
        {
            QMessageBox::critical(this, "Error", "Fallo al actualizar el componente en la base de datos.");
        } else {
            refreshModel();
        }
        dlg->close();
        dlg->deleteLater();
    });
    connect(dlg, &AddDialog::cancelled, dlg, &AddDialog::close);
}
References AddDialog::accepted(), AddDialog::cancelled(), InventoryItem::cantidad, InventoryItem::fechaAdquisicion, AddDialog::getDate(), InventoryManager::getItemById(), AddDialog::getLocation(), AddDialog::getName(), AddDialog::getQuantity(), AddDialog::getType(), manager, model, InventoryItem::nombre, proxy, tableView, InventoryItem::tipo, InventoryItem::ubicacion, and InventoryManager::updateItem().
onExport
void MainWindow::onExport () private slot
Genera y exporta un reporte del inventario en formato CSV.
Abre un diálogo de sistema para seleccionar la ruta de guardado y utiliza la clase helper CSVReport para generar el archivo.
Definition at line 470 of file mainwindow.cpp.
{
    QString filename = QFileDialog::getSaveFileName(
        this, "Guardar Reporte CSV", "reporte.csv", "Archivos CSV (*.csv)");
    if (filename.isEmpty()) return;
    CSVReport report;
    // Obtiene todos los items mediante el manager y genera el archivo
    if (report.generate(manager.getAllItems(), filename)) {
        QMessageBox::information(this, "Éxito", "El reporte ha sido exportado correctamente.");
    } else {
        QMessageBox::critical(this, "Error de Exportación", "No se pudo escribir el archivo en la ruta seleccionada.");
    }
}
References CSVReport::generate(), InventoryManager::getAllItems(), and manager.
onLoadDefaults()
void MainWindow::onLoadDefaults () private
Carga un conjunto de datos de prueba (Seed Data).
Inserta aproximadamente 50 ítems predefinidos en la base de datos. Útil para pruebas y demostraciones iniciales.
Definition at line 387 of file mainwindow.cpp.
{
    QList<QList<QString>> defaults = {
      {"Resistor 10kΩ", "Electrónico", "100", "Cajón A1", "2024-01-10"},
      {"Capacitor 100nF", "Electrónico", "80", "Cajón A1", "2024-01-12"},
      {"Diodo 1N4148", "Electrónico", "150", "Cajón A2", "2024-02-01"},
      {"LED Rojo 5mm", "Electrónico", "200", "Cajón A2", "2024-03-05"},
      {"Transistor 2N3904", "Electrónico", "120", "Cajón A3", "2024-03-10"},
      {"Potenciómetro 10k", "Electrónico", "15", "Cajón B1", "2024-02-20"},
      {"Motor DC 6V", "Electrónico", "10", "Estante B2", "2024-03-03"},
      {"Sensor HC-SR04", "Sensor", "12", "Estante C1", "2024-02-28"},
      {"Arduino Uno", "Microcontrolador", "4", "Estante C2", "2023-11-22"},
      {"Protoboard", "Herramienta", "10", "Estante C3", "2023-12-10"},
      {"Raspberry Pi Pico", "Microcontrolador", "6", "Estante C2", "2024-01-30"},
      {"Relé 5V", "Electrónico", "30", "Cajón A3", "2024-01-11"},
      {"Cable Dupont (m/m)", "Accesorio", "300", "Cajón A1", "2024-01-05"},
      {"Cable Dupont (h/h)", "Accesorio", "300", "Cajón A1", "2024-01-05"},
      {"Batería 9V", "Electrónico", "25", "Estante D1", "2024-02-10"},
      {"Multímetro Digital", "Instrumento", "3", "Mesa Taller", "2023-12-10"},
      {"Osciloscopio", "Instrumento", "1", "Mesa Taller", "2023-09-10"},
      {"Fuente DC 30V", "Instrumento", "2", "Mesa Taller", "2023-09-10"},
      {"Sensor PIR SR505", "Sensor", "20", "Estante C1", "2024-01-05"},
      {"Sensor DHT11", "Sensor", "15", "Estante C1", "2024-01-08"},
      {"Sensor DHT22", "Sensor", "10", "Estante C1", "2024-01-08"},
      {"ESP32-CAM", "Microcontrolador", "7", "Estante C2", "2024-02-01"},
      {"ESP8266", "Microcontrolador", "10", "Estante C2", "2024-02-02"},
      {"Cámara Web USB", "Computación", "5", "Estante D2", "2023-11-11"},
      {"Router TP-Link", "Red", "3", "Estante D2", "2023-12-01"},
      {"Switch Lógico", "Electrónico", "100", "Cajón A4", "2024-01-22"},
      {"Cables USB", "Accesorio", "30", "Cajón B3", "2023-12-28"},
      {"Rollo Cinta Aislante", "Herramienta", "20", "Cajón B3", "2023-12-30"},
      {"Soldador 60W", "Herramienta", "2", "Mesa Taller", "2023-12-15"},
      {"Estaño", "Consumible", "10", "Cajón B1", "2023-12-15"},
      {"Alcohol Isopropílico", "Limpieza", "4", "Estante E1", "2024-01-02"},
      {"Guantes Nitrilo", "Laboratorio", "200", "Armario F1", "2024-01-01"},
      {"Termómetro Digital", "Laboratorio", "3", "Estante E2", "2023-12-10"},
      {"Placa de Calentamiento", "Laboratorio", "1", "Estante E3", "2023-11-20"},
      {"Cronómetro", "Laboratorio", "2", "Cajón B4", "2023-12-09"},
      {"Lupa de Banco", "Herramienta", "2", "Mesa Taller", "2023-10-15"},
      {"Extensión Eléctrica", "Hogar", "8", "Estante D1", "2023-10-10"},
      {"Bombillo LED 12W", "Hogar", "20", "Estante D1", "2023-09-10"},
      {"Tomacorriente", "Hogar", "40", "Estante D1", "2023-09-10"},
      {"Interruptor de Pared", "Hogar", "40", "Estante D1", "2023-09-10"},
      {"Control Remoto IR", "Electrónico", "15", "Cajón A2", "2024-02-01"},
      {"Buzzer 5V", "Electrónico", "40", "Cajón A3", "2024-02-03"},
      {"Servo SG90", "Electrónico", "15", "Cajón A3", "2024-02-10"},
      {"Switch de Palanca", "Electrónico", "50", "Cajón A4", "2024-02-11"},
      {"Jack DC 5.5mm", "Electrónico", "60", "Cajón A4", "2024-02-11"},
      {"Pinzas de Cocodrilo", "Accesorio", "50", "Cajón B3", "2024-01-01"},
      {"Termistor NTC 10k", "Sensor", "80", "Cajón A2", "2024-01-20"}
    };
    for (const auto &item : defaults) {
        manager.addItem(item[0], item[1], item[2].toInt(), item[3], item[4]);
    }
    refreshModel();
    QMessageBox::information(this, "Carga Completa", "Se han cargado exitosamente los componentes por defecto.");
}
References InventoryManager::addItem(), manager, and refreshModel().
onLowStock
void MainWindow::onLowStock () private slot
Analiza el stock actual y resalta visualmente los ítems críticos.
Itera sobre todas las filas del modelo proxy.
Compara la cantidad con lowStockThreshold.
Si es menor, modifica el Qt::BackgroundRole de la celda para pintarla de rojo claro.
Genera una lista de nombres de productos bajos en stock y la muestra en un MessageBox.
Definition at line 494 of file mainwindow.cpp.
{
    QStringList lowStockItems;
    for (int r = 0; r < proxy->rowCount(); r++) {
        // Índice de la columna 'Cantidad' (columna 3)
        QModelIndex idxQty = proxy->index(r, 3);
        int qty = idxQty.data().toInt();
        if (qty < lowStockThreshold) {
            // Pintar toda la fila (iterando columnas)
            for (int c = 0; c < proxy->columnCount(); c++) {
                tableView->model()->setData(
                    proxy->index(r, c),
                    QColor(255, 200, 200), // Rojo claro
                    Qt::BackgroundRole
                );
            }
            // Agregar nombre a la lista de alerta
            QModelIndex idxName = proxy->index(r, 1);
            lowStockItems << idxName.data().toString();
        }
    }
    if (!lowStockItems.isEmpty()) {
        QMessageBox::warning(this, "Alerta de Stock Bajo",
            "Los siguientes ítems están por debajo del mínimo:\n\n" + lowStockItems.join("\n"));
    } else {
        QMessageBox::information(this, "Stock Saludable", "No hay elementos con stock bajo.");
    }
}
References lowStockThreshold, proxy, and tableView.
onRestoreDefaults()
void MainWindow::onRestoreDefaults () private
Restaura la base de datos a su estado original (vacía y luego recargada).
Warning
Esta acción ejecuta un DELETE FROM inventario, borrando todos los datos existentes.
Definition at line 451 of file mainwindow.cpp.
{
    if (QMessageBox::question(this, "Restaurar Fábrica",
                              "¿Seguro que deseas borrar TODO el inventario y restaurar los datos por defecto?\nEsta acción no se puede deshacer.")
        != QMessageBox::Yes)
        return;
    QSqlQuery q;
    q.exec("DELETE FROM inventario");
    onLoadDefaults();
    QMessageBox::information(this, "Restauración", "La base de datos ha sido restaurada.");
}
References onLoadDefaults().
onSearch
void MainWindow::onSearch (const QString & text) private slot
Filtra la tabla en tiempo real según el texto ingresado.
Parameters
text Cadena de búsqueda. Se busca coincidencia en cualquier columna.
Definition at line 531 of file mainwindow.cpp.
{
    proxy->setFilterFixedString(text);
}
References proxy.
refreshModel()
void MainWindow::refreshModel () private
Actualiza la vista recargando los datos desde la base de datos SQL.
Ejecuta de nuevo la consulta SELECT sobre el modelo y reasigna los nombres de las cabeceras para una visualización amigable.
Definition at line 541 of file mainwindow.cpp.
{
    model->setQuery("SELECT id, nombre, tipo, cantidad, ubicacion, fechaAdquisicion "
                    "FROM inventario ORDER BY id DESC");
    model->setHeaderData(0, Qt::Horizontal, "ID");
    model->setHeaderData(1, Qt::Horizontal, "Nombre");
    model->setHeaderData(2, Qt::Horizontal, "Tipo");
    model->setHeaderData(3, Qt::Horizontal, "Cantidad");
    model->setHeaderData(4, Qt::Horizontal, "Ubicación");
    model->setHeaderData(5, Qt::Horizontal, "Fecha Adquisición");
    tableView->resizeColumnsToContents();
}
References model, and tableView.
Member Data Documentation
lowStockThreshold
const int MainWindow::lowStockThreshold = 5 private
Definition at line 111 of file mainwindow.h.
manager
InventoryManager MainWindow::manager private
Definition at line 105 of file mainwindow.h.
model
QSqlQueryModel* MainWindow::model private
Definition at line 106 of file mainwindow.h.
proxy
QSortFilterProxyModel* MainWindow::proxy private
Definition at line 107 of file mainwindow.h.
searchEdit
QLineEdit* MainWindow::searchEdit private
Definition at line 109 of file mainwindow.h.
tableView
QTableView* MainWindow::tableView private
Definition at line 108 of file mainwindow.h.
The documentation for this class was generated from the following files:
include/mainwindow.h
src/mainwindow.cpp