PROYECTO FINAL ALSE: AddDialog Class Reference
AddDialog Class Reference
Diálogo modal para la creación y edición de componentes.
#include <mainwindow.h>
Signals
void accepted ()
void cancelled ()
Public Member Functions
AddDialog (QWidget *parent=nullptr)
Constructor de la clase AddDialog.
QString getName () const
Obtiene el nombre ingresado por el usuario.
QString getType () const
Obtiene el tipo de componente ingresado.
int getQuantity () const
Obtiene la cantidad seleccionada.
QString getLocation () const
Obtiene la ubicación física del componente.
QDate getDate () const
Obtiene la fecha de adquisición seleccionada.
Private Slots
void onOk ()
Slot llamado al presionar "Agregar/Aceptar".
void onCancel ()
Slot llamado al presionar "Cancelar".
Private Attributes
QLineEdit * nameEdit
QLineEdit * typeEdit
QSpinBox * qtySpin
QLineEdit * locEdit
QDateEdit * dateEdit
Detailed Description
Diálogo modal para la creación y edición de componentes.
Esta clase hereda de QWidget (usado como ventana) y proporciona un formulario con validaciones básicas para ingresar Nombre, Tipo, Cantidad, Ubicación y Fecha.
Definition at line 28 of file mainwindow.h.
Constructor & Destructor Documentation
AddDialog()
AddDialog::AddDialog (QWidget * parent = nullptr) explicit
Constructor de la clase AddDialog.
Configura el layout vertical, inicializa los widgets de entrada (QLineEdit, QSpinBox, etc.) y conecta los botones de Aceptar/Cancelar a sus respectivos slots.
Parameters
parent Widget padre (opcional), por defecto es nullptr.
Definition at line 76 of file mainwindow.cpp.
                                    : QWidget(parent)
{
    setWindowTitle("Agregar componente");
    QVBoxLayout *v = new QVBoxLayout(this);
    // Campos de entrada
    nameEdit = new QLineEdit(); nameEdit->setPlaceholderText("Nombre");
    typeEdit = new QLineEdit(); typeEdit->setPlaceholderText("Tipo");
    qtySpin = new QSpinBox(); qtySpin->setRange(0, 1000000); qtySpin->setValue(1);
    locEdit = new QLineEdit(); locEdit->setPlaceholderText("Ubicación");
    dateEdit = new QDateEdit(QDate::currentDate()); dateEdit->setCalendarPopup(true);
    QPushButton *btnOk = new QPushButton("Agregar");
    QPushButton *btnCancel = new QPushButton("Cancelar");
    // Construcción del formulario
    v->addWidget(new QLabel("Nombre:"));    v->addWidget(nameEdit);
    v->addWidget(new QLabel("Tipo:"));      v->addWidget(typeEdit);
    v->addWidget(new QLabel("Cantidad:"));  v->addWidget(qtySpin);
    v->addWidget(new QLabel("Ubicación:")); v->addWidget(locEdit);
    v->addWidget(new QLabel("Fecha adquisición:")); v->addWidget(dateEdit);
    // Botonera
    QHBoxLayout *h = new QHBoxLayout();
    h->addWidget(btnOk);
    h->addWidget(btnCancel);
    v->addLayout(h);
    // Conexiones de señales
    connect(btnOk, &QPushButton::clicked, this, &AddDialog::onOk);
    connect(btnCancel, &QPushButton::clicked, this, &AddDialog::onCancel);
    // Asignación de nombres de objeto para búsqueda dinámica (findChild)
    nameEdit->setObjectName("nameEdit");
    typeEdit->setObjectName("typeEdit");
    qtySpin->setObjectName("qtySpin");
    locEdit->setObjectName("locEdit");
    dateEdit->setObjectName("dateEdit");
}
References dateEdit, locEdit, nameEdit, onCancel(), onOk(), qtySpin, and typeEdit.
Member Function Documentation
accepted
void AddDialog::accepted () signal
cancelled
void AddDialog::cancelled () signal
getDate()
QDate AddDialog::getDate () const
Obtiene la fecha de adquisición seleccionada.
Returns
Objeto QDate con la fecha.
Definition at line 144 of file mainwindow.cpp.
{ return dateEdit->date(); }
References dateEdit.
getLocation()
QString AddDialog::getLocation () const
Obtiene la ubicación física del componente.
Returns
QString con la ubicación.
Definition at line 138 of file mainwindow.cpp.
{ return locEdit->text().trimmed(); }
References locEdit.
getName()
QString AddDialog::getName () const
Obtiene el nombre ingresado por el usuario.
Returns
QString con el texto limpio de espacios al inicio y final (trimmed).
Definition at line 120 of file mainwindow.cpp.
{ return nameEdit->text().trimmed(); }
References nameEdit.
getQuantity()
int AddDialog::getQuantity () const
Obtiene la cantidad seleccionada.
Returns
Entero con el valor del QSpinBox.
Definition at line 132 of file mainwindow.cpp.
{ return qtySpin->value(); }
References qtySpin.
getType()
QString AddDialog::getType () const
Obtiene el tipo de componente ingresado.
Returns
QString con el tipo (trimmed).
Definition at line 126 of file mainwindow.cpp.
{ return typeEdit->text().trimmed(); }
References typeEdit.
onCancel
void AddDialog::onCancel () private slot
Slot llamado al presionar "Cancelar".
Emite la señal cancelled() para cerrar el diálogo sin cambios.
Definition at line 156 of file mainwindow.cpp.
{ emit cancelled(); }
References cancelled().
onOk
void AddDialog::onOk () private slot
Slot llamado al presionar "Agregar/Aceptar".
Emite la señal accepted() para notificar a la ventana principal.
Definition at line 150 of file mainwindow.cpp.
{ emit accepted(); }
References accepted().
Member Data Documentation
dateEdit
QDateEdit* AddDialog::dateEdit private
Definition at line 54 of file mainwindow.h.
locEdit
QLineEdit* AddDialog::locEdit private
Definition at line 53 of file mainwindow.h.
nameEdit
QLineEdit* AddDialog::nameEdit private
Definition at line 50 of file mainwindow.h.
qtySpin
QSpinBox* AddDialog::qtySpin private
Definition at line 52 of file mainwindow.h.
typeEdit
QLineEdit* AddDialog::typeEdit private
Definition at line 51 of file mainwindow.h.
The documentation for this class was generated from the following files:
include/mainwindow.h
src/mainwindow.cpp